### ISSUE TITLE
Functions for flipping normals and flipping winding order.

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_data_py#26]

**Comment by ScanMountGoat** [comment]
I've added a script to the examples directory. Just changing winding order seems to be enough for some imports that people have had trouble with. This should really be fixed in a 3d modeling program rather than with Python, so I don't have any plans of adding dedicated functions to ssbh_data_py for this. There are a lot of variables that affect how the final shading normals get calculated, so having the visual feedback and editing capabilities of a modeling program are essential.
